interface: xyz.openbmc_project.Control.FanPwm
service_hash: /sys/devices/platform/ahb/ahb:apb/1e786000.pwm-tacho-controller/ahb/apb/pwm-tacho-controller@1e786000
fans:
  - fan1_0
  - fan1_1
  - fan2_0
  - fan2_1
  - fan3_0
  - fan3_1
  - fan4_0
  - fan4_1
